version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "appspec.yml"
    - "public/**/*"
    - "src/**/*"
    - "package.json"
    - "build/**/*"
    - "scripts/**/*"
